# SPDX-FileCopyrightText: 2024 KUNBUS GmbH
# SPDX-License-Identifier: GPL-2.0-only

include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "kernel/linter-checkpatch.yml"

checkpatch:
  variables:
    CHECKPATCH_ARGS: "--no-tree"
  allow_failure: true
